# Generated by Django 4.2.5 on 2023-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(help_text='max length of coupon can be 20 characters', max_length=20),
        ),
    ]
