# Generated by Django 4.2.5 on 2023-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_dob_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='It should be a 10 digit number only', max_length=10, null=True),
        ),
    ]
