# Generated by Django 4.2.5 on 2023-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
