# Generated by Django 4.2.5 on 2023-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False, help_text='Tick it if you have replied to the customers query'),
        ),
    ]
