# Generated by Django 4.2.5 on 2023-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handyman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Provider (Handyman)',
            },
        ),
    ]
