# Generated by Django 4.2.5 on 2023-09-19 17:32

import django.contrib.auth.password_validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0002_profile_bio_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('card_image', models.ImageField(upload_to='service_cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_service_name', models.CharField(max_length=255)),
                ('sub_service_card_image', models.ImageField(help_text='Small card image on left', upload_to='service_cards')),
                ('sub_service_main_image', models.ImageField(help_text='Big card image on Right, which we scroll', upload_to='service_cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickfix.services')),
            ],
            options={
                'verbose_name_plural': 'Sub Services',
            },
        ),
    ]
