# Generated by Django 4.2.5 on 2023-09-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0002_handyman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handyman',
            options={'verbose_name_plural': 'Service Provider'},
        ),
    ]
