# Generated by Django 4.2.5 on 2023-09-29 05:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0002_contact_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
