# Generated by Django 4.2.5 on 2023-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0003_alter_handyman_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handyman',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
