# Generated by Django 4.2.5 on 2023-09-19 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0003_services_alter_profile_password_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservices',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservices',
            name='detailed_price',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
