# Generated by Django 4.2.5 on 2023-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0003_alter_subservices_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals_and_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deals_and_discount_banners')),
                ('heading', models.CharField(max_length=255)),
                ('percent_off', models.CharField(help_text='write here only percentage i.e. (10, 20, 30 etc)', max_length=3)),
                ('subheading', models.CharField(max_length=255)),
            ],
        ),
    ]
