# Generated by Django 4.2.5 on 2023-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0004_subservices_description_subservices_detailed_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial_images')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
