# Generated by Django 4.2.5 on 2023-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0004_alter_handyman_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handyman',
            name='mobile_number',
            field=models.CharField(help_text='It should be 10 digit number', max_length=10),
        ),
    ]
