# Generated by Django 4.2.5 on 2023-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0005_alter_deals_and_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals_and_discount',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deals_and_discount',
            name='percent_off',
            field=models.CharField(blank=True, help_text='write here only percentage i.e. (10, 20, 30 etc)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='deals_and_discount',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
