# Generated by Django 4.2.5 on 2023-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
