# Generated by Django 4.2.5 on 2023-10-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0007_remove_deals_and_discount_subheading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
