# Generated by Django 4.2.5 on 2023-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0007_alter_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
