# Generated by Django 4.2.5 on 2023-10-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0008_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='enable_contact',
            field=models.BooleanField(default=False),
        ),
    ]
