# Generated by Django 4.2.5 on 2023-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0009_services_enable_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='sub_service_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
