# Generated by Django 4.2.5 on 2023-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0009_alter_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
