# Generated by Django 4.2.5 on 2023-10-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0010_alter_subservices_sub_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_contact_rent',
            field=models.BooleanField(default=True, help_text='Tick if you want to show Contact Form for Rent'),
        ),
    ]
