# Generated by Django 4.2.5 on 2023-10-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0011_services_is_contact_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=13)),
                ('quantity', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('is_amc_call', models.BooleanField(default=False)),
                ('is_rent_call', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calls Booked',
            },
        ),
    ]
