# Generated by Django 4.2.5 on 2023-10-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0013_alter_bookcall_duration_alter_bookcall_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='enable_contact',
        ),
        migrations.RemoveField(
            model_name='services',
            name='is_contact_rent',
        ),
        migrations.AddField(
            model_name='services',
            name='show_contact_form',
            field=models.BooleanField(default=False, help_text="Tick it for 'IT on RENT' and 'AMC' Services"),
        ),
        migrations.AddField(
            model_name='services',
            name='show_rent_form',
            field=models.BooleanField(default=True, help_text='Tick - IT on Rent, Untick - AMC Services'),
        ),
    ]
