# Generated by Django 4.2.5 on 2023-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0014_remove_services_enable_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcall',
            name='product',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
