# Generated by Django 4.2.5 on 2023-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
