# Generated by Django 4.2.5 on 2023-09-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_cost',
        ),
    ]
