# Generated by Django 4.2.5 on 2023-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='start_time',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='time_slot',
            field=models.CharField(choices=[('10-12', '10-12'), ('12-2', '12-2'), ('2-4', '2-4'), ('4-7', '4-7')], default=1, max_length=10),
        ),
    ]
