# Generated by Django 4.2.5 on 2023-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartitem_start_time_cartitem_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='time_slot',
            field=models.CharField(choices=[('10AM - 12PM', '10-12'), ('12PM - 2PM', '12-2'), ('2PM - 4PM', '2-4'), ('4PM - 7PM', '4-7')], default=1, max_length=20),
        ),
    ]
