# Generated by Django 4.2.5 on 2023-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='time_slot',
            field=models.CharField(choices=[('10-12', '10AM - 12PM'), ('12-2', '12PM - 2PM'), ('2-4', '2PM - 4PM'), ('4-7', '4PM - 7PM')], default=1, max_length=20),
        ),
    ]
