# Generated by Django 4.2.5 on 2023-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='time_slot',
            field=models.CharField(choices=[('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('4pm-7pm', '4pm-7pm')], default=1, max_length=20),
        ),
    ]
