# Generated by Django 4.2.5 on 2023-09-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartitem_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='isPaid',
        ),
    ]
