# Generated by Django 4.2.5 on 2023-10-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash on Delivery'), ('razorpay', 'Online - Razorpay')], default='razorpay', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Rescheduled', 'Rescheduled'), ('Job Completed', 'Job Completed'), ('Booking Not Accepted', 'Booking Not Accepted')], default='Upcoming', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Booked Today'), (2, 'Out For Service'), (3, 'Service Begun'), (4, 'Service Completed')], default=1, null=True),
        ),
    ]
