# Generated by Django 4.2.5 on 2023-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Rescheduled', 'Rescheduled'), ('Job Completed', 'Job Completed'), ('Booking Not Accepted', 'Booking Not Accepted')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('Booked Today', 'Upcoming'), ('Out For Service', 'Out For Service'), ('Service Begun', 'Service Begun'), ('Service Completed', 'Service Completed')], max_length=30, null=True),
        ),
    ]
