# Generated by Django 4.2.5 on 2023-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0002_order_booking_status_order_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('Booked Today', 'Booked Today'), ('Out For Service', 'Out For Service'), ('Service Begun', 'Service Begun'), ('Service Completed', 'Service Completed')], max_length=30, null=True),
        ),
    ]
