# Generated by Django 4.2.5 on 2023-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0002_order_payment_mode_alter_order_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash_on_delivery', 'Cash on Delivery'), ('razorpay', 'Razorpay')], default='razorpay', max_length=20, null=True),
        ),
    ]
