# Generated by Django 4.2.5 on 2023-10-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_cart_cost'),
        ('razorpayAPI', '0003_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.billingdetails'),
        ),
    ]
