# Generated by Django 4.2.5 on 2023-09-27 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickfix', '0002_handyman'),
        ('razorpayAPI', '0003_alter_order_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clickfix.handyman'),
        ),
    ]
