# Generated by Django 4.2.5 on 2023-10-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0004_alter_order_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
