# Generated by Django 4.2.5 on 2023-10-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0005_alter_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show_amount_in_bookings',
            field=models.BooleanField(default=True),
        ),
    ]
