# Generated by Django 4.2.5 on 2023-10-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpayAPI', '0006_order_show_amount_in_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='show_amount_in_bookings',
            field=models.BooleanField(default=False),
        ),
    ]
